from bacil_parser import parse
from ecoli_parser import parse
from humocell_parser import parse
from humoegf_parser import parse
from lact_parser import parse
from musphoini1_parser import parse
from musphoini2_parser import parse
from musphoini_parser import parse
from phosida import parse